language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.4
    - otp_release: 19.1
      elixir: 1.3.4
    - otp_release: 19.1
      elixir: 1.4.0-rc.0
notifications:
  email:
    - mitch@rokkincat.com
